### ISSUE TITLE
Kevin Golden Geometry Assignment

### ISSUE THREAD

**Issue by kwg58** [ga-wdi-exercises/js_geometry#56]
https://github.com/kwg58/js_geometry

**Comment by RobertAKARobin** [comment]
I see what the problem is! This is the code for `js_calculator` -- not `js_geometry`!

**Comment by kwg58** [comment]
Wow, that’s stupid!!  What kid of idiot would make a stupid mistake like th

Oh, never mind.  

Thanks.
